import Head from 'next/head'
import Header from '../components/Header';

export default function Home() {
  return (
    <div className='colo'>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build hulu 2.0</h1>
      <Header />
    </div>
  )
}
